# For more info on HTTP files go to https://aka.ms/vs/httpfile

@vezetoseg = http://localhost:5000/api/vezetoseg

GET {{vezetoseg}}

###

GET {{vezetoseg}}/1

###

POST {{vezetoseg}}
Content-Type: application/json

{
  "nev": "Teszt Elek",
  "email" : "elek@teszt.hu",
  "megbizas" : "vezetõ"
}

###

PUT {{vezetoseg}}/5
Content-Type: application/json

{
  "nev": "Teszt Elek",
  "email" : "elek@teszt.hu",
  "megbizas" : "vezetõ helyettes"
}

###

DELETE {{vezetoseg}}/5

###